import "./globals.css";
import type { Metadata } from "next";
import Navbar from "@/components/navbar.component";
import { ReactQueryProvider } from "@/providers/react-query.provider";
export const metadata: Metadata = {
  title: "Trello",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={"h-full"}>
      <body className={"dark bg-gray-900 h-full"}>
        <ReactQueryProvider>
          <Navbar />
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
